### ISSUE TITLE
支持64位hook么?

### ISSUE THREAD

**Issue by menglinxi** [turing-technician/FastHook#1]
如题

**Comment by turing-technician** [comment]
支持的，支持arm64

**Comment by EvanWater** [comment]
我用小米4c的miui7无法hook报地址错误，android 5.1. 但用miui10可以。 错误是abi arm很奇怪。  
![image](https://user-images.githubusercontent.com/44297980/54806711-d3efa400-4cb5-11e9-9d13-04c67ab667ae.png)
