### ISSUE TITLE
可以整合virtualapp使用吗?

### ISSUE THREAD

**Issue by menglinxi** [turing-technician/FastHook#2]
可以整合virtualapp使用吗?

**Comment by turing-technician** [comment]
这周末我再出个结合VirtualApp hook微信的样例

**Comment by turing-technician** [comment]
FastHook + VirtualApp的教程见：[https://www.jianshu.com/p/48f165b56fdc](https://www.jianshu.com/p/48f165b56fdc)
项目地址：[https://github.com/turing-technician/VirtualFastHook](https://github.com/turing-technician/VirtualFastHook)

**Comment by menglinxi** [comment]
太感谢了...
