### ISSUE TITLE
不支持x86么?

### ISSUE THREAD

**Issue by wjy000** [turing-technician/FastHook#3]
不支持x86么?

**Comment by turing-technician** [comment]
目前不支持，因为我做的项目不涉及到x86，主要是Thumb2和Arm64，如果有需求，后续我会加上

**Comment by lozn00** [comment]
话说和whale比怎么样

**Comment by turing-technician** [comment]
之前没关注过，刚才去看了下，就ART hook而言跟其他框架类似，还是用的备份原方法的方案，这是有先天缺陷的，细节上的处理有欠缺。FastHook的方案有先天优势，实现也简洁，其他框架则繁琐。可以看看[FastHook——远超其他同类框架的优异稳定性](https://blog.csdn.net/TuringTechnician/article/details/88737754)

**Comment by lozn00** [comment]
大佬有交流群不，我现在在whale群，哈哈
