### ISSUE TITLE
lenovo x3c50 android 6.0 crash

### ISSUE THREAD

**Issue by hetianlong0** [turing-technician/FastHook#4]
使用lennove x3c50 android 6.0.1 rewrite, replace模式都报错，一个错误为：

 03-23 17:14:31.010  6742  6742 I FastHookManager: QuickHookTrampoline[14] 0 e0 40 9d
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickHookTrampoline[15] 7f 0 0 0
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[0] e0 0 0 58
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[1] e8 b 40 d1
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[2] 1f 1 40 b9
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[3] ff 3 1 d1
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[4] f3 d3 2 a9
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[5] 91 0 0 58
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[6] 20 2 1f d6
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[7] 80 a3 e5 70
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[8] 0 0 0 0
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[9] 1c f0 7d 74
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickTargetTrampoline[10] 0 0 0 0
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[0] 1f 20 3 d5
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[1] e8 b 40 d1
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[2] 1f 1 40 b9
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[3] ff 3 1 d1
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[4] f3 d3 2 a9
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[5] 91 0 0 58
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[6] 20 2 1f d6
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[7] 0 0 0 0
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[8] 0 0 0 0
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[9] 1c f0 7d 74
03-23 17:14:31.010  6742  6742 I FastHookManager: QuickOriginalTrampoline[10] 0 0 0 0
03-23 17:14:31.010  6742  6742 I FastHookManager: Forward NewEntry:0x7f9d40d000
03-23 17:14:31.010  6742  6742 I FastHookManager: Mprotect:0 Pagesize:4096 Alignment:12
03-23 17:14:31.010  6742  6742 I FastHookManager: TargetCode[0] 50 0 0 58
03-23 17:14:31.010  6742  6742 I FastHookManager: TargetCode[1] 0 2 1f d6
03-23 17:14:31.010  6742  6742 I FastHookManager: TargetCode[2] 0 f0 40 9d
03-23 17:14:31.010  6742  6742 I FastHookManager: TargetCode[3] 7f 0 0 0
03-23 17:14:31.010  6742  6742 D FastHookManager: JumpTrampoline:0x7f9d410000 QuickHookTrampoline:0x7f9d40f000 QuickTargetTrampoline:0x7f9d40d000 QuickOriginalTrampoline:0x7f9d40e000
03-23 17:14:31.010  6742  6742 D FastHookManager: doHook finish
03-23 17:14:31.010  6742  6742 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 6742 (ian.fasthookapp)
03-23 17:14:31.110   442   442 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-23 17:14:31.110   442   442 F DEBUG   : Build fingerprint: 'Lenovo/X3c50/X3c50:6.0.1/MMB29M/VIBEUI_V3.1_1626_5.565.1_ST_X3c50:user/release-keys'
03-23 17:14:31.110   442   442 F DEBUG   : Revision: '0'
03-23 17:14:31.110   442   442 F DEBUG   : ABI: 'arm64'
03-23 17:14:31.120   442   442 F DEBUG   : pid: 6742, tid: 6742, name: ian.fasthookapp  >>> pers.turing.technician.fasthookapp <<<
03-23 17:14:31.120   442   442 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
03-23 17:14:31.120   442   442 F DEBUG   :     x0   0000007fb3112180  x1   0000007fe26a2754  x2   0000007fb3112180  x3   0000000000570000
03-23 17:14:31.120   442   442 F DEBUG   :     x4   0000000000430000  x5   0000000000000000  x6   0000007fb30fa000  x7   0000007fb30fc9a8
03-23 17:14:31.120   442   442 F DEBUG   :     x8   0000007f9df1f280  x9   0000000000000000  x10  0000000000000000  x11  0000007fe26a2db8
03-23 17:14:31.130   442   442 F DEBUG   :     x12  0000000000000001  x13  0000000000000000  x14  0000007fb31035bc  x15  0000000000000000
03-23 17:14:31.130   442   442 F DEBUG   :     x16  0000007fb31035b8  x17  0000000000000000  x18  0000007fb37bba00  x19  0000000012ddf400
03-23 17:14:31.130   442   442 F DEBUG   :     x20  0000007f9df09fdc  x21  0000007fb37bba00  x22  0000000012cae280  x23  0000000000000000
03-23 17:14:31.130   442   442 F DEBUG   :     x24  0000000070cbdbd0  x25  000027be00001a56  x26  000027be00001a56  x27  0000000012ceb130
03-23 17:14:31.130   442   442 F DEBUG   :     x28  0000000071d568d5  x29  0000007fe26a2730  x30  0000007fa02ed71c
03-23 17:14:31.130   442   442 F DEBUG   :     sp   0000007fe26a26f0  pc   0000007f9df0a014  pstate 0000000060000000
03-23 17:14:31.130   442   442 F DEBUG   :
03-23 17:14:31.130   442   442 F DEBUG   : backtrace:
03-23 17:14:31.130   442   442 F DEBUG   :     #00 pc 0000000000003014  /data/app/pers.turing.technician.fasthookapp-1/lib/arm64/libfasthook.so (DisableJITInline+56)
03-23 17:14:31.130   442   442 F DEBUG   :     #01 pc 0000000000592718  /data/app/pers.turing.technician.fasthookapp-1/oat/arm64/base.odex (offset 0x2f5000) (void pers.turing.technician.fasthook.FastHookManager.disableJITInline()+124)
03-23 17:14:31.130   442   442 F DEBUG   :     #02 pc 0000000000594aa4  /data/app/pers.turing.technician.fasthookapp-1/oat/arm64/base.odex (offset 0x2f5000) (void pers.turing.technician.fasthook.FastHookManager.doHook(java.lang.String, java.lang.ClassLoader, java.lang.ClassLoader, java.lang.ClassLoader, java.lang.ClassLoader, boolean)+6296)
03-23 17:14:31.130   442   442 F DEBUG   :     #03 pc 000000000059a5b8  /data/app/pers.turing.technician.fasthookapp-1/oat/arm64/base.odex (offset 0x2f5000) (void pers.turing.technician.fasthookapp.MainActivity$1.onClick(android.view.View)+300)
03-23 17:14:31.130   442   442 F DEBUG   :     #04 pc 000000000379aa7c  /system/framework/arm64/boot.oat (offset 0x206f000)
03-23 17:14:31.260   442   442 F DEBUG   :
03-23 17:14:31.260   442   442 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_03
03-23 17:14:31.260  1501  6765 W ActivityManager:   Force finishing activity pers.turing.technician.fasthookapp/.MainActivity
03-23 17:14:31.260   442   442 E DEBUG   : AM write failed: Broken pipe
03-23 17:14:31.260  1501  6767 D ActivityManager: notifyAppAppExecption: pers.turing.technician.fasthookapp
03-23 17:14:31.260  1501  2026 I BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
03-23 17:14:31.260  1501  6765 D ActivityManager: ===================
03-23 17:14:31.260  1501  6765 D ActivityManager: r: ActivityRecord{34bac9a u0 pers.turing.technician.fasthookapp/.MainActivity t266 f}
03-23 17:14:31.260  1501  6765 D ActivityManager: next: null
03-23 17:14:31.260  1501  6765 D ActivityManager: task: TaskRecord{2b1e869 #266 A=pers.turing.technician.fasthookapp U=0 sz=1}
03-23 17:14:31.260  1501  6765 D ActivityManager: topTask: TaskRecord{2b1e869 #266 A=pers.turing.technician.fasthookapp U=0 sz=1}
03-23 17:14:31.260  1501  6765 D ActivityManager: r.frontOfTask: true
03-23 17:14:31.260  1501  6765 D ActivityManager: task.isOverHomeStack(): false
03-23 17:14:31.260  1501  6765 D ActivityManager: mLastTask: null
03-23 17:14:31.260  1501  6765 D ActivityManager: top: null
03-23 17:14:31.260  1501  6765 D ActivityManager: ===================
03-23 17:14:31.260  1501  6765 I ActivityManager: startPausingLocked.updateThumbnail is run here

**Comment by turing-technician** [comment]
非常感谢反馈！由于项目彻底抛弃了7.0之前的版本，所以有些改动没有做好兼容，导致出现了问题。现在已经修复，你看看还会不会出现问题。有任何问题都欢迎提出。

**Comment by hetianlong0** [comment]
你好，经过测试一个该bug已经解决了。非常迅速啊！

**Comment by EvanWater** [comment]
> 非常感谢反馈！由于项目彻底抛弃了7.0之前的版本，所以有些改动没有做好兼容，导致出现了问题。现在已经修复，你看看还会不会出现问题。有任何问题都欢迎提出。

请问抛弃的包括7.0版本吗？

**Comment by turing-technician** [comment]
之前说的是我工作的项目，跟这个没关系。我会尽力支持每个版本。

**Comment by EvanWater** [comment]
感谢大大，已测5.1可以了。原来的不行！
