### ISSUE TITLE
lennove x3c50 android 6.0 另外一个crash

### ISSUE THREAD

**Issue by hetianlong0** [turing-technician/FastHook#5]
03-23 17:29:21.200  7087  7087 D FastHookManager: doHook target:testNativeStatic hook:hookNativeStaticTest forward:forwardNativeStaticTest model:2 retry:0
03-23 17:29:21.200  7087  7087 D FastHookManager: do replace hook for native method
03-23 17:29:21.200  7087  7087 I FastHookManager: Type:4 Trampoline:0x7f9d48d000
03-23 17:29:21.200  7087  7087 I FastHookManager: Type:5 Trampoline:0x7f9d48c000
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline:0x7f9d48d000 HookMethod:0x7f9e528bf8
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[0] 60 0 0 58
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[1] 10 18 40 f9
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[2] 0 2 1f d6
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[3] f8 8b 52 9e
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[4] 7f 0 0 0
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[0] 60 0 0 58
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[1] 90 0 0 58
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[2] 0 2 1f d6
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[3] 98 87 52 9e
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[4] 7f 0 0 0
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[5] 2c 8b 2f a0
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[6] 7f 0 0 0
03-23 17:29:21.200  7087  7087 I FastHookManager: Target NewEntry:0x7f9d48d000
03-23 17:29:21.200  7087  7087 I FastHookManager: Forward NewEntry:0x7f9d48c000
03-23 17:29:21.200  7087  7087 D FastHookManager: QuickHookTrampoline:0x7f9d48d000 QuickTargetTrampoline:0x7f9d48c000
03-23 17:29:21.200  7087  7087 D FastHookManager: doHook finish
03-23 17:29:21.200  7087  7087 D FastHookManager: doHook Mode:2 TargetMethod[android.widget.TextView,setText,Ljava/lang/CharSequence;] HookMethod[pers.turing.technician.fasthookapp.hook.HookMethodInfo,hookSystemTest,Ljava/lang/Object;Ljava/lang/CharSequence;] ForwardMethod[pers.turing.technician.fasthookapp.hook.HookMethodInfo,forwardSystemTest,Ljava/lang/Object;Ljava/lang/CharSequence;]
03-23 17:29:21.200  7087  7087 D FastHookManager: doHook target:setText hook:hookSystemTest forward:forwardSystemTest model:2 retry:0
03-23 17:29:21.200  7087  7087 I FastHookManager: Type:4 Trampoline:0x7f9d48b000
03-23 17:29:21.200  7087  7087 I FastHookManager: Type:5 Trampoline:0x7f9d48a000
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline:0x7f9d48b000 HookMethod:0x7f9e528ca0
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[0] 60 0 0 58
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[1] 10 18 40 f9
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[2] 0 2 1f d6
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[3] a0 8c 52 9e
03-23 17:29:21.200  7087  7087 I FastHookManager: HookTrampoline[4] 7f 0 0 0
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[0] 60 0 0 58
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[1] 90 0 0 58
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[2] 0 2 1f d6
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[3] 80 a3 e5 70
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[4] 0 0 0 0
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[5] 0 0 0 0
03-23 17:29:21.200  7087  7087 I FastHookManager: TargetTrampoline[6] 0 0 0 0
03-23 17:29:21.200  7087  7087 I FastHookManager: Target NewEntry:0x7f9d48b000
03-23 17:29:21.200  7087  7087 I FastHookManager: Forward NewEntry:0x7f9d48a000
03-23 17:29:21.200  7087  7087 D FastHookManager: QuickHookTrampoline:0x7f9d48b000 QuickTargetTrampoline:0x7f9d48a000
03-23 17:29:21.200  7087  7087 D FastHookManager: doHook finish
03-23 17:29:21.200  7087  7087 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 7087 (ian.fasthookapp)
03-23 17:29:21.260   442   442 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-23 17:29:21.260   442   442 F DEBUG   : Build fingerprint: 'Lenovo/X3c50/X3c50:6.0.1/MMB29M/VIBEUI_V3.1_1626_5.565.1_ST_X3c50:user/release-keys'
03-23 17:29:21.260   442   442 F DEBUG   : Revision: '0'
03-23 17:29:21.260   442   442 F DEBUG   : ABI: 'arm64'
03-23 17:29:21.260   442   442 F DEBUG   : pid: 7087, tid: 7087, name: ian.fasthookapp  >>> pers.turing.technician.fasthookapp <<<
03-23 17:29:21.260   442   442 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
03-23 17:29:21.270   442   442 F DEBUG   :     x0   0000007fb3112180  x1   0000007fe26a2754  x2   0000007fb3112180  x3   0000000000570000
03-23 17:29:21.270   442   442 F DEBUG   :     x4   0000000000430000  x5   0000000000000000  x6   0000007fb30fa000  x7   0000007fb30fc9a8
03-23 17:29:21.270   442   442 F DEBUG   :     x8   0000007f9d4bf280  x9   0000000000000000  x10  0000000000000000  x11  0000007fe26a2db8
03-23 17:29:21.270   442   442 F DEBUG   :     x12  0000000000000001  x13  0000000000000000  x14  0000007fb31035bc  x15  0000000000000000
03-23 17:29:21.270   442   442 F DEBUG   :     x16  0000007fb31035b8  x17  0000000000000000  x18  0000007fb37bba00  x19  0000000012dde800
03-23 17:29:21.270   442   442 F DEBUG   :     x20  0000007f9d4a9fdc  x21  0000007fb37bba00  x22  0000000012cae430  x23  0000000000000000
03-23 17:29:21.270   442   442 F DEBUG   :     x24  0000000070cbdbd0  x25  000027be00001baf  x26  000027be00001baf  x27  0000000012cf3640
03-23 17:29:21.270   442   442 F DEBUG   :     x28  0000000071d568d5  x29  0000007fe26a2730  x30  0000007fa02ed71c
03-23 17:29:21.270   442   442 F DEBUG   :     sp   0000007fe26a26f0  pc   0000007f9d4aa014  pstate 0000000060000000
03-23 17:29:21.270   442   442 F DEBUG   :
03-23 17:29:21.270   442   442 F DEBUG   : backtrace:
03-23 17:29:21.270   442   442 F DEBUG   :     #00 pc 0000000000003014  /data/app/pers.turing.technician.fasthookapp-1/lib/arm64/libfasthook.so (DisableJITInline+56)
03-23 17:29:21.270   442   442 F DEBUG   :     #01 pc 0000000000592718  /data/app/pers.turing.technician.fasthookapp-1/oat/arm64/base.odex (offset 0x2f5000) (void pers.turing.technician.fasthook.FastHookManager.disableJITInline()+124)
03-23 17:29:21.270   442   442 F DEBUG   :     #02 pc 0000000000594aa4  /data/app/pers.turing.technician.fasthookapp-1/oat/arm64/base.odex (offset 0x2f5000) (void pers.turing.technician.fasthook.FastHookManager.doHook(java.lang.String, java.lang.ClassLoader, java.lang.ClassLoader, java.lang.ClassLoader, java.lang.ClassLoader, boolean)+6296)
03-23 17:29:21.270   442   442 F DEBUG   :     #03 pc 000000000059a988  /data/app/pers.turing.technician.fasthookapp-1/oat/arm64/base.odex (offset 0x2f5000) (void pers.turing.technician.fasthookapp.MainActivity$2.onClick(android.view.View)+300)
03-23 17:29:21.270   442   442 F DEBUG   :     #04 pc 000000000379aa7c  /system/framework/arm64/boot.oat (offset 0x206f000)
03-23 17:29:21.400   442   442 F DEBUG   :
03-23 17:29:21.400   442   442 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_06
03-23 17:29:21.400   442   442 E DEBUG   : AM write failed: Broken pipe
03-23 17:29:21.400  1501  2026 I BootReceiver: Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
03-23 17:29:21.400  1501  7223 W ActivityManager:   Force finishing activity pers.turing.technician.fasthookapp/.MainActivity
03-23 17:29:21.400  1501  7223 I SurfaceControl: Rect(0, 72 - 1080, 1920)
03-23 17:29:21.400  1501  7223 D ActivityManager: ===================
03-23 17:29:21.400  1501  7223 D ActivityManager: r: ActivityRecord{3835754 u0 pers.turing.technician.fasthookapp/.MainActivity t270 f}
03-23 17:29:21.400  1501  7223 D ActivityManager: next: null
03-23 17:29:21.400  1501  7223 D ActivityManager: task: TaskRecord{52af57c #270 A=pers.turing.technician.fasthookapp U=0 sz=1}
03-23 17:29:21.400  1501  7223 D ActivityManager: topTask: TaskRecord{52af57c #270 A=pers.turing.technician.fasthookapp U=0 sz=1}
03-23 17:29:21.410   412   412 I SurfaceFlinger: strok layer name=none
03-23 17:29:21.400  1501  7223 D ActivityManager: r.frontOfTask: true

**Comment by turing-technician** [comment]
非常感谢反馈！由于项目彻底抛弃了7.0之前的版本，所以有些改动没有做好兼容，导致出现了问题。现在已经修复，你看看还会不会出现问题。有任何问题都欢迎提出。

**Comment by hetianlong0** [comment]
你好，经过测试一个该bug已经解决了。非常迅速啊！
